"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio          = [ 1, 3, 0 ]
sort_by        = "modified"
sort_dir_first = true
linemode       = "none"
show_hidden    = false
show_symlink   = true
scrolloff      = 5

[preview]
image_delay = 20

[input]
cd_title     = " Change directory "
create_title = " Create "
rename_title = " Rename "
filter_title = " Filter "
find_title   = [ " Find next ", " Find previous " ]
shell_title  = [ " Shell ", " Shell (block) " ]

[confirm]
trash_title       = " Trash {n} selected file{s}? "
delete_title      = " Permanently delete {n} selected file{s}? "
overwrite_title   = " Overwrite file? "
overwrite_content = " Will overwrite the following file: "

quit_title   = " Quit? "
quit_content = " The following task is still running: "

[select]
open_title = " Open with: "

[which]
sort_by        = "none"
sort_sensitive = false
sort_reverse   = false
sort_translit  = false
